export const CREATE_CUSTOMER_REQ = 'CREATE_CUSTOMER_REQ'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL'

export const CREATE_ACCOUNT_REQ = 'CREATE_ACCOUNT_REQ'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CREATE_ACCOUNT_FAIL = 'CREATE_ACCOUNT_FAIL'

export const CREATE_CARD_REQ = 'CREATE_CARD_REQ'
export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS'
export const CREATE_CARD_FAIL = 'CREATE_CARD_FAIL'

export const DELETE_CUSTOMER_REQ = 'DELETE_CARD_REQ'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CARD_SUCCESS'
export const DELETE_CUSTOMER_FAIL = 'DELETE_CARD_FAIL'

export const DELETE_ACCOUNT_REQ = 'DELETE_ACCOUNT_REQ'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL'

export const DELETE_CARD_REQ = 'DELETE_CARD_REQ'
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS'
export const DELETE_CARD_FAIL = 'DELETE_CARD_FAIL'
